language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-nanocyte-component' ]; then cd .. && eval "mv $currentfolder generator-nanocyte-component" && cd generator-nanocyte-component; fi
